Favorits hinzugefügt:
SAKPaaS/documentation pull request #1
Opened 2020-04-18 11:30 UTC by Leaqua07

-Endpunkte hinzugefügt:
1. '/users/self/favorits/{id}':
- post und delete
2. '/users/self/favorits/':
- get

2020-04-18 11:44 UTC, jstsddg requested changes
Statt `favorits` heißt es `favorites`, das habe ich vorhin glaube ich falsch gesagt. Ich fixe das gerade kurz.

2020-04-18 11:44 UTC, MrKraboom commented on api/v2/openapi.yaml
> +              $ref: '#/components/schemas/Location'
Brauchen wir überhaupt einen `requestBody`? Die ID steht ja schon in der URL

2020-04-18 11:44 UTC, MrKraboom commented on api/v2/openapi.yaml
> +          description: Malformed request
Hier könnte zusätzlich noch ein `404` auftreten, wenn die Location nicht existiert und ein `401`, wenn der man nicht eingeloggt ist.

2020-04-18 11:44 UTC, MrKraboom commented on api/v2/openapi.yaml
> +              $ref: '#/components/schemas/Location'
Hier brauchen wir glaube ich ebenso keinen `requestBody`.

2020-04-18 11:44 UTC, MrKraboom commented on api/v2/openapi.yaml
> +          description: Malformed request
Hier könnte auch ein `401`, bzw. `404` auftreten.

2020-04-18 11:44 UTC, MrKraboom commented on api/v2/openapi.yaml
> +          description: Not found
Ich glaube hier kann kein `404` auftreten, da wir wenn man keine Favoriten hat einfach eine leere Liste `[]` zurück geben.

2020-04-18 11:44 UTC, MrKraboom commented on api/v2/openapi.yaml
> +          description: Not found
Aber auch hier könnte wieder ein `401` auftreten.

2020-04-18 12:03 UTC, MrKraboom commented on api/v2/openapi.yaml
> +          description: Not found
Ich glaube hier kann kein `404` auftreten, da wir wenn man keine Favoriten hat einfach eine leere Liste `[]` zurück geben.

Aber hier könnte auch wieder ein `401` auftreten, wenn der Benutzer nicht angemeldet ist.

2020-04-18 12:04 UTC, MrKraboom commented
Ich habe den Tippfehler entfernt, die Endpunkt Reihenfolge angepasst (get, post, delete) und ein fehlendes Schema hinzugefügt.

2020-04-18 13:53 UTC, MrKraboom commented
Die `Location`s sollten noch ein `favorite`-Flag bekommen ob die Location ein Favorit ist. Möglicherweise `null` wenn man nicht eingeloggt ist?

2020-04-18 21:14 UTC, jstsddg submitted a review, later dismissed
LGTM

2020-04-18 21:15 UTC, MrKraboom commented
@SAKPaaS/frontend Gerne auch ein Review vom Frontend, damit wir hier nicht unbrauchbares implementieren.

2020-04-18 22:50 UTC, nclskfm submitted a review, later dismissed

2020-04-18 22:50 UTC, nclskfm commented on api/v2/openapi.yaml
> +      responses:
kann nicht hier auch ein `401` auftreten? Wenn der User nicht eingeloggt ist? Oder was passiert dann?

2020-04-19 09:01 UTC, MrKraboom commented on api/v2/openapi.yaml
> +      responses:
Ja stimmt, @Leaqua07 kannst du das gerade kurz hinzufügen oder soll ich das nachher machen?

2020-04-19 16:06 UTC, MrKraboom commented on api/v2/openapi.yaml
> +      responses:
Ich hab's jetzt gerade einfach kurz eingefügt-

2020-04-19 16:07 UTC, jstsddg approved these changes
401 Implementiert, sieht gut aus

2020-04-19 17:42 UTC, benfu99 approved these changes

2020-04-19 18:01 UTC, merged