Update openapi.yaml
SAKPaaS/documentation pull request #6
Opened 2020-05-01 17:43 UTC by DerObstKlauer

Ich habe den Endpunkt für die Locationtypes analog zu den existierenden definiert (TINF-331).

2020-05-02 08:29 UTC, jstsddg requested changes

2020-05-02 08:29 UTC, MrKraboom commented on api/v2/openapi.yaml
> +  '/users/self/locations/types':
Warum denn `/users/self/...`? Der Endpunkt hat doch nichts mit den Benutzern zu tun, sondern nur mit den Locations. Der ist ja immerhin auch öffentlich zugänglich.
Also eher `/locations/types` würde passen.

2020-05-02 08:29 UTC, MrKraboom commented on api/v2/openapi.yaml
> +        '404':
Wie kann denn hier ein `404` auftreten?

2020-05-02 08:29 UTC, MrKraboom commented on api/v2/openapi.yaml
> +        - locationtypes
Dieser Tag wird als Überschrift in swagger angezeigt, vielleicht wäre dann `Locations` oder `Location Types` schöner.

2020-05-02 23:48 UTC, DerObstKlauer commented on api/v2/openapi.yaml
> +  '/users/self/locations/types':
Danke, hab ich übersehen

2020-05-03 14:14 UTC, jstsddg submitted a review, later dismissed
Sieht so gut für mich aus!

2020-05-04 19:24 UTC, nclskfm requested changes

2020-05-04 19:24 UTC, nclskfm commented on api/v2/openapi.yaml
> +      description: Locationtypes
sollte `Location Types` sein, damit es einheitlich ist. (vgl. https://github.com/SAKPaaS/documentation/pull/4)

2020-05-05 10:43 UTC, nclskfm approved these changes
lgtm

2020-05-05 10:44 UTC, r-franzke approved these changes

2020-05-05 10:44 UTC, merged